#   ___  ____           ___  ___            _        ___  ______ _____
#  |  \/  (_)          |  \/  |           (_)      / _ \ | ___ \_   _|
#  | .  . |_ _ __   ___| .  . | __ _ _ __  _  __ _/ /_\ \| |_/ / | |
#  | |\/| | | '_ \ / _ \ |\/| |/ _` | '_ \| |/ _` |  _  ||  __/  | |
#  | |  | | | | | |  __/ |  | | (_| | | | | | (_| | | | || |    _| |_
#  \_|  |_/_|_| |_|\___\_|  |_/\__,_|_| |_|_|\__,_\_| |_/\_|    \___/
#
# Author: MineManiaUK Staff

kerb:
  client_name: ""
  server_port: 5000
  server_address: ""
  password: ""
  max_wait_time_millis: 400

database:
  connection_string: ""
  database_name: ""
